export const LEAVE_APPLICATION_CREATE_REQUEST = 'LEAVE_APPLICATION_CREATE_REQUEST';
export const LEAVE_APPLICATION_CREATE_SUCCESS = 'LEAVE_APPLICATION_CREATE_SUCCESS';
export const LEAVE_APPLICATION_CREATE_FAIL = 'LEAVE_APPLICATION_CREATE_FAIL';
export const LEAVE_APPLICATION_CREATE_RESET = 'LEAVE_APPLICATION_CREATE_RESET';

export const LEAVE_APPLICATION_DETAILS_REQUEST = 'LEAVE_APPLICATION_DETAILS_REQUEST';
export const LEAVE_APPLICATION_DETAILS_SUCCESS = 'LEAVE_APPLICATION_DETAILS_SUCCESS';
export const LEAVE_APPLICATION_DETAILS_FAIL = 'LEAVE_APPLICATION_DETAILS_FAIL';
export const LEAVE_APPLICATION_DETAILS_RESET = 'LEAVE_APPLICATION_DETAILS_RESET';

export const LEAVE_APPLICATION_UPDATE_EMPLOYEE_REQUEST = 'LEAVE_APPLICATION_CREATE_EMPLOYEE_REQUEST';
export const LEAVE_APPLICATION_UPDATE_EMPLOYEE_SUCCESS = 'LEAVE_APPLICATION_CREATE_EMPLOYEE_SUCCESS';
export const LEAVE_APPLICATION_UPDATE_EMPLOYEE_FAIL = 'LEAVE_APPLICATION_CREATE_EMPLOYEE_FAIL';
export const LEAVE_APPLICATION_UPDATE_EMPLOYEE_RESET = 'LEAVE_APPLICATION_CREATE_EMPLOYEE_RESET';

export const LEAVE_APPLICATION_DETAILS_EMPLOYEE_REQUEST = 'LEAVE_APPLICATION_DETAILS_EMPLOYEE_REQUEST';
export const LEAVE_APPLICATION_DETAILS_EMPLOYEE_SUCCESS = 'LEAVE_APPLICATION_DETAILS_EMPLOYEE_SUCCESS';
export const LEAVE_APPLICATION_DETAILS_EMPLOYEE_FAIL = 'LEAVE_APPLICATION_DETAILS_EMPLOYEE_FAIL';
export const LEAVE_APPLICATION_DETAILS_EMPLOYEE_RESET = 'LEAVE_APPLICATION_DETAILS_EMPLOYEE_RESET';

export const LEAVE_APPLICATION_DETAILS_ID_REQUEST = 'LEAVE_APPLICATION_DETAILS_ID_REQUEST';
export const LEAVE_APPLICATION_DETAILS_ID_SUCCESS = 'LEAVE_APPLICATION_DETAILS_ID_SUCCESS';
export const LEAVE_APPLICATION_DETAILS_ID_FAIL = 'LEAVE_APPLICATION_DETAILS_ID_FAIL';
export const LEAVE_APPLICATION_DETAILS_ID_RESET = 'LEAVE_APPLICATION_DETAILS_ID_RESET';
