export const MYLEAVE_DETAILS_REQUEST = 'MYLEAVE_DETAILS_REQUEST'
export const MYLEAVE_DETAILS_SUCCESS = 'MYLEAVE_DETAILS_SUCCESS'
export const MYLEAVE_DETAILS_FAIL = 'MYLEAVE_DETAILS_FAIL'
export const MYLEAVE_DETAILS_RESET = 'MYLEAVE_DETAILS_RESET'

export const MYLEAVE_UPDATE_REQUEST = 'MYLEAVE_UPDATE_REQUEST'
export const MYLEAVE_UPDATE_SUCCESS = 'MYLEAVE_UPDATE_SUCCESS'
export const MYLEAVE_UPDATE_FAIL = 'MYLEAVE_UPDATE_FAIL'
export const MYLEAVE_UPDATE_RESET = 'MYLEAVE_UPDATE_RESET'

export const MYLEAVE_CREATE_REQUEST = 'MYLEAVE_CREATE_REQUEST'
export const MYLEAVE_CREATE_SUCCESS = 'MYLEAVE_CREATE_SUCCESS'
export const MYLEAVE_CREATE_FAIL = 'MYLEAVE_CREATE_FAIL'
export const MYLEAVE_CREATE_RESET = 'MYLEAVE_CREATE_RESET'

export const MYLEAVE_CREATE_EMPLOYEE_REQUEST = 'MYLEAVE_CREATE_EMPLOYEE_REQUEST'
export const MYLEAVE_CREATE_EMPLOYEE_SUCCESS = 'MYLEAVE_CREATE_EMPLOYEE_SUCCESS'
export const MYLEAVE_CREATE_EMPLOYEE_FAIL = 'MYLEAVE_CREATE_EMPLOYEE_FAIL'
export const MYLEAVE_CREATE_EMPLOYEE_RESET = 'MYLEAVE_CREATE_EMPLOYEE_RESET'

export const MYLEAVE_DETAILS_EMPLOYEE_REQUEST = 'MYLEAVE_DETAILS_EMPLOYEE_REQUEST'
export const MYLEAVE_DETAILS_EMPLOYEE_SUCCESS = 'MYLEAVE_DETAILS_EMPLOYEE_SUCCESS'
export const MYLEAVE_DETAILS_EMPLOYEE_FAIL = 'MYLEAVE_DETAILS_EMPLOYEE_FAIL'
export const MYLEAVE_DETAILS_EMPLOYEE_RESET = 'MYLEAVE_DETAILS_EMPLOYEE_RESET'